import { Listing } from '@/types';

export const MOCK_LISTINGS: Listing[] = [
  {
    id: '1',
    titleAz: '3-otaqlı mənzil, Nəsimi rayonu',
    titleTr: '3 odalı daire, Nesimi ilçesi',
    titleEn: '3-room apartment, Nasimi district',
    descriptionAz: 'Bakının mərkəzində, Nəsimi rayonunda, tam təmirli 3 otaqlı mənzil. Yüksək mərtəbədə yerləşir, şəhər mənzərəsi möhtəşəmdir. Bütün kommunal xidmətlər mövcuddur.',
    descriptionTr: 'Bakü\'nün merkezinde, Nesimi ilçesinde, tam tadilatlı 3 odalı daire. Yüksek katta yer almakta olup şehir manzarası muhteşemdir. Tüm altyapı hizmetleri mevcuttur.',
    descriptionEn: 'Fully renovated 3-room apartment in the center of Baku, Nasimi district. Located on a high floor with stunning city views. All utilities available.',
    price: 285000,
    currency: 'AZN',
    category: 'SALE',
    propertyType: 'APARTMENT',
    status: 'ACTIVE',
    isFeatured: true,
    isNew: true,
    city: 'Bakı',
    district: 'Nəsimi',
    address: 'Nizami küçəsi 45',
    latitude: 40.3777,
    longitude: 49.8920,
    area: 120,
    rooms: 3,
    bathrooms: 2,
    floor: 8,
    totalFloors: 16,
    buildYear: 2018,
    hasParking: true,
    hasGarage: false,
    hasBalcony: true,
    hasElevator: true,
    hasFurniture: true,
    hasAC: true,
    hasHeating: true,
    hasInternet: true,
    hasSecurity: true,
    hasPool: false,
    hasGym: false,
    images: [
      { id: 'img1', url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80', alt: 'Living room', isPrimary: true, order: 0 },
      { id: 'img2', url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80', alt: 'Exterior', isPrimary: false, order: 1 },
      { id: 'img3', url: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80', alt: 'Kitchen', isPrimary: false, order: 2 },
    ],
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-03-01T10:00:00Z',
    viewCount: 342,
  },
  {
    id: '2',
    titleAz: '2-otaqlı mənzil, Xətai rayonu',
    titleTr: '2 odalı daire, Hətay ilçesi',
    titleEn: '2-room apartment, Khatai district',
    descriptionAz: 'Xətai rayonunda, yeni tikili binada 2 otaqlı mənzil. Əla nəqliyyat əlaqəsi, rahat infrastruktur.',
    descriptionTr: 'Hətay ilçesinde yeni binada 2 odalı daire. Mükemmel ulaşım bağlantısı, rahat altyapı.',
    descriptionEn: '2-room apartment in a new building in Khatai district. Excellent transport links and convenient infrastructure.',
    price: 1800,
    currency: 'AZN',
    category: 'RENT',
    propertyType: 'APARTMENT',
    status: 'ACTIVE',
    isFeatured: false,
    isNew: true,
    city: 'Bakı',
    district: 'Xətai',
    area: 75,
    rooms: 2,
    bathrooms: 1,
    floor: 5,
    totalFloors: 12,
    buildYear: 2022,
    hasParking: true,
    hasGarage: false,
    hasBalcony: true,
    hasElevator: true,
    hasFurniture: true,
    hasAC: true,
    hasHeating: true,
    hasInternet: true,
    hasSecurity: false,
    hasPool: false,
    hasGym: false,
    images: [
      { id: 'img4', url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80', alt: 'Apartment', isPrimary: true, order: 0 },
      { id: 'img5', url: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80', alt: 'Bedroom', isPrimary: false, order: 1 },
    ],
    createdAt: '2026-03-05T10:00:00Z',
    updatedAt: '2026-03-05T10:00:00Z',
    viewCount: 218,
  },
  {
    id: '3',
    titleAz: 'Həyət evi, Sabunçu rayonu',
    titleTr: 'Müstakil ev, Sabunçu ilçesi',
    titleEn: 'Private house, Sabunchu district',
    descriptionAz: 'Sabunçu rayonunda 3 mərtəbəli həyət evi. Geniş bağ sahəsi, qaraj, tam avadanlıqlı.',
    descriptionTr: 'Sabunçu ilçesinde 3 katlı müstakil ev. Geniş bahçe, garaj, tam donanımlı.',
    descriptionEn: '3-storey private house in Sabunchu district. Large garden, garage, fully equipped.',
    price: 450000,
    currency: 'AZN',
    category: 'SALE',
    propertyType: 'HOUSE',
    status: 'ACTIVE',
    isFeatured: true,
    isNew: false,
    city: 'Bakı',
    district: 'Sabunçu',
    area: 280,
    rooms: 6,
    bathrooms: 3,
    floor: 1,
    totalFloors: 3,
    buildYear: 2015,
    hasParking: true,
    hasGarage: true,
    hasBalcony: true,
    hasElevator: false,
    hasFurniture: false,
    hasAC: true,
    hasHeating: true,
    hasInternet: true,
    hasSecurity: true,
    hasPool: true,
    hasGym: false,
    images: [
      { id: 'img6', url: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80', alt: 'House', isPrimary: true, order: 0 },
      { id: 'img7', url: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80', alt: 'Garden', isPrimary: false, order: 1 },
    ],
    createdAt: '2026-02-20T10:00:00Z',
    updatedAt: '2026-02-20T10:00:00Z',
    viewCount: 487,
  },
  {
    id: '4',
    titleAz: 'Villa, Mərdəkan, dəniz görünüşlü',
    titleTr: 'Villa, Mardakan, deniz manzaralı',
    titleEn: 'Villa, Mardakan, sea view',
    descriptionAz: 'Mərdəkanda möhtəşəm dəniz görünüşlü villa. Şəxsi hovuz, geniş bağ, 5 yataq otağı.',
    descriptionTr: 'Mardakan\'da muhteşem deniz manzaralı villa. Özel havuz, geniş bahçe, 5 yatak odası.',
    descriptionEn: 'Stunning sea-view villa in Mardakan. Private pool, large garden, 5 bedrooms.',
    price: 1200000,
    currency: 'AZN',
    category: 'SALE',
    propertyType: 'VILLA',
    status: 'ACTIVE',
    isFeatured: true,
    isNew: false,
    city: 'Bakı',
    district: 'Mərdəkan',
    area: 480,
    rooms: 5,
    bathrooms: 4,
    floor: 1,
    totalFloors: 2,
    buildYear: 2020,
    hasParking: true,
    hasGarage: true,
    hasBalcony: true,
    hasElevator: false,
    hasFurniture: true,
    hasAC: true,
    hasHeating: true,
    hasInternet: true,
    hasSecurity: true,
    hasPool: true,
    hasGym: true,
    images: [
      { id: 'img8', url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80', alt: 'Villa', isPrimary: true, order: 0 },
      { id: 'img9', url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80', alt: 'Pool', isPrimary: false, order: 1 },
    ],
    createdAt: '2026-02-15T10:00:00Z',
    updatedAt: '2026-02-15T10:00:00Z',
    viewCount: 631,
  },
  {
    id: '5',
    titleAz: 'Ofis sahəsi, Nərimanov rayonu',
    titleTr: 'Ofis alanı, Nərimanov ilçesi',
    titleEn: 'Office space, Narimanov district',
    descriptionAz: 'Nərimanov rayonunda, biznes mərkəzinin 3-cü mərtəbəsində açıq plan ofis sahəsi. 24 saat mühafizə.',
    descriptionTr: 'Nərimanov ilçesinde, iş merkezinin 3. katında açık plan ofis alanı. 7/24 güvenlik.',
    descriptionEn: 'Open-plan office space on the 3rd floor of a business center in Narimanov district. 24/7 security.',
    price: 3500,
    currency: 'AZN',
    category: 'RENT',
    propertyType: 'OFFICE',
    status: 'ACTIVE',
    isFeatured: false,
    isNew: true,
    city: 'Bakı',
    district: 'Nərimanov',
    area: 150,
    rooms: 4,
    bathrooms: 2,
    floor: 3,
    totalFloors: 10,
    buildYear: 2019,
    hasParking: true,
    hasGarage: false,
    hasBalcony: false,
    hasElevator: true,
    hasFurniture: false,
    hasAC: true,
    hasHeating: true,
    hasInternet: true,
    hasSecurity: true,
    hasPool: false,
    hasGym: false,
    images: [
      { id: 'img10', url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80', alt: 'Office', isPrimary: true, order: 0 },
    ],
    createdAt: '2026-03-10T10:00:00Z',
    updatedAt: '2026-03-10T10:00:00Z',
    viewCount: 156,
  },
  {
    id: '6',
    titleAz: '1-otaqlı mənzil, Yasamal rayonu',
    titleTr: '1 odalı daire, Yasamal ilçesi',
    titleEn: '1-room apartment, Yasamal district',
    descriptionAz: 'Yasamal rayonunda, tam təmirli 1 otaqlı mənzil. Metro stansiyasına 5 dəqiqəlik piyada məsafə.',
    descriptionTr: 'Yasamal ilçesinde, tam tadilatlı 1 odalı daire. Metro istasyonuna 5 dakika yürüme mesafesi.',
    descriptionEn: 'Fully renovated 1-room apartment in Yasamal district. 5-minute walk to metro station.',
    price: 900,
    currency: 'AZN',
    category: 'RENT',
    propertyType: 'APARTMENT',
    status: 'ACTIVE',
    isFeatured: false,
    isNew: false,
    city: 'Bakı',
    district: 'Yasamal',
    area: 45,
    rooms: 1,
    bathrooms: 1,
    floor: 3,
    totalFloors: 9,
    buildYear: 2010,
    hasParking: false,
    hasGarage: false,
    hasBalcony: true,
    hasElevator: true,
    hasFurniture: true,
    hasAC: false,
    hasHeating: true,
    hasInternet: true,
    hasSecurity: false,
    hasPool: false,
    hasGym: false,
    images: [
      { id: 'img11', url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80', alt: 'Studio', isPrimary: true, order: 0 },
    ],
    createdAt: '2026-03-12T10:00:00Z',
    updatedAt: '2026-03-12T10:00:00Z',
    viewCount: 289,
  },
  {
    id: '7',
    titleAz: 'Torpaq sahəsi, Abşeron',
    titleTr: 'Arsa, Abşeron',
    titleEn: 'Land plot, Absheron',
    descriptionAz: 'Abşeron yarımadasında tikinti üçün yararlı torpaq sahəsi. Bütün kommunikasiyalar mövcuddur.',
    descriptionTr: 'Abşeron yarımadasında inşaata uygun arsa. Tüm altyapı mevcut.',
    descriptionEn: 'Land plot suitable for construction on the Absheron peninsula. All utilities available.',
    price: 180000,
    currency: 'AZN',
    category: 'SALE',
    propertyType: 'LAND',
    status: 'ACTIVE',
    isFeatured: false,
    isNew: false,
    city: 'Abşeron',
    district: 'Maştağa',
    area: 600,
    hasParking: false,
    hasGarage: false,
    hasBalcony: false,
    hasElevator: false,
    hasFurniture: false,
    hasAC: false,
    hasHeating: false,
    hasInternet: false,
    hasSecurity: false,
    hasPool: false,
    hasGym: false,
    images: [
      { id: 'img12', url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80', alt: 'Land', isPrimary: true, order: 0 },
    ],
    createdAt: '2026-02-28T10:00:00Z',
    updatedAt: '2026-02-28T10:00:00Z',
    viewCount: 94,
  },
  {
    id: '8',
    titleAz: '4-otaqlı mənzil, Binəqədi rayonu',
    titleTr: '4 odalı daire, Binəqədi ilçesi',
    titleEn: '4-room apartment, Binagadi district',
    descriptionAz: 'Binəqədi rayonunda geniş 4 otaqlı mənzil. Iki balkon, geniş mətbəx, rahat ərazidə.',
    descriptionTr: 'Binəqədi ilçesinde geniş 4 odalı daire. İki balkon, geniş mutfak, sakin bölgede.',
    descriptionEn: 'Spacious 4-room apartment in Binagadi district. Two balconies, large kitchen, quiet area.',
    price: 195000,
    currency: 'AZN',
    category: 'SALE',
    propertyType: 'APARTMENT',
    status: 'ACTIVE',
    isFeatured: false,
    isNew: true,
    city: 'Bakı',
    district: 'Binəqədi',
    area: 155,
    rooms: 4,
    bathrooms: 2,
    floor: 6,
    totalFloors: 14,
    buildYear: 2021,
    hasParking: true,
    hasGarage: false,
    hasBalcony: true,
    hasElevator: true,
    hasFurniture: false,
    hasAC: false,
    hasHeating: true,
    hasInternet: true,
    hasSecurity: false,
    hasPool: false,
    hasGym: false,
    images: [
      { id: 'img13', url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80', alt: 'Apartment', isPrimary: true, order: 0 },
    ],
    createdAt: '2026-03-15T10:00:00Z',
    updatedAt: '2026-03-15T10:00:00Z',
    viewCount: 178,
  },
  {
    id: '9',
    titleAz: 'Kommersiya obyekti, Nizami küçəsi',
    titleTr: 'Ticari alan, Nizami caddesi',
    titleEn: 'Commercial space, Nizami street',
    descriptionAz: 'Nizami küçəsinin mərkəzində, 1-ci mərtəbədə kommersiya sahəsi. Yüksək insan axını, əla görünürlük.',
    descriptionTr: 'Nizami caddesinin merkezinde, zemin katta ticari alan. Yüksek yaya trafiği, mükemmel görünürlük.',
    descriptionEn: 'Commercial space on the ground floor in the center of Nizami street. High foot traffic, excellent visibility.',
    price: 5000,
    currency: 'AZN',
    category: 'RENT',
    propertyType: 'COMMERCIAL',
    status: 'ACTIVE',
    isFeatured: true,
    isNew: false,
    city: 'Bakı',
    district: 'Nəsimi',
    address: 'Nizami küçəsi 88',
    area: 85,
    floor: 1,
    totalFloors: 8,
    buildYear: 2005,
    hasParking: false,
    hasGarage: false,
    hasBalcony: false,
    hasElevator: true,
    hasFurniture: false,
    hasAC: true,
    hasHeating: true,
    hasInternet: true,
    hasSecurity: true,
    hasPool: false,
    hasGym: false,
    images: [
      { id: 'img14', url: 'https://images.unsplash.com/photo-1604328698692-f76ea9498e76?w=800&q=80', alt: 'Commercial', isPrimary: true, order: 0 },
    ],
    createdAt: '2026-03-08T10:00:00Z',
    updatedAt: '2026-03-08T10:00:00Z',
    viewCount: 203,
  },
  {
    id: '10',
    titleAz: '5-otaqlı həyət evi, Sumqayıt',
    titleTr: '5 odalı müstakil ev, Sumgayıt',
    titleEn: '5-room private house, Sumgayit',
    descriptionAz: 'Sumqayıtda geniş həyət evi. Böyük bağ sahəsi, garaj, tam yenilənmiş.',
    descriptionTr: 'Sumgayıt\'ta geniş müstakil ev. Büyük bahçe, garaj, tamamen yenilenmiş.',
    descriptionEn: 'Spacious private house in Sumgayit. Large garden, garage, completely renovated.',
    price: 320000,
    currency: 'AZN',
    category: 'SALE',
    propertyType: 'HOUSE',
    status: 'ACTIVE',
    isFeatured: false,
    isNew: false,
    city: 'Sumqayıt',
    district: 'Mərkəz',
    area: 220,
    rooms: 5,
    bathrooms: 2,
    floor: 1,
    totalFloors: 2,
    buildYear: 2012,
    hasParking: true,
    hasGarage: true,
    hasBalcony: true,
    hasElevator: false,
    hasFurniture: false,
    hasAC: false,
    hasHeating: true,
    hasInternet: true,
    hasSecurity: false,
    hasPool: false,
    hasGym: false,
    images: [
      { id: 'img15', url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80', alt: 'House', isPrimary: true, order: 0 },
    ],
    createdAt: '2026-02-25T10:00:00Z',
    updatedAt: '2026-02-25T10:00:00Z',
    viewCount: 312,
  },
];

export function getListingTitle(listing: Listing, locale: string): string {
  if (locale === 'tr') return listing.titleTr;
  if (locale === 'en') return listing.titleEn;
  return listing.titleAz;
}

export function getListingDescription(listing: Listing, locale: string): string {
  if (locale === 'tr') return listing.descriptionTr;
  if (locale === 'en') return listing.descriptionEn;
  return listing.descriptionAz;
}

export function getPrimaryImage(listing: Listing): string {
  const primary = listing.images.find((img) => img.isPrimary);
  return primary?.url ?? listing.images[0]?.url ?? '/images/placeholder.jpg';
}

export function formatPrice(price: number, currency: string): string {
  return `${price.toLocaleString('az-AZ')} ${currency}`;
}
