import { PrismaClient } from '../src/generated/prisma/client';
import { PrismaBetterSqlite3 } from '@prisma/adapter-better-sqlite3';
import path from 'path';

const dbPath = path.join(process.cwd(), 'prisma', 'dev.db');
const adapter = new PrismaBetterSqlite3({ url: `file:${dbPath}` });
const prisma = new PrismaClient({ adapter });

const listings = [
  {
    titleAz: '3 otaqlı mənzil — Nəsimi rayonu, Nizami küçəsi',
    titleTr: '3 odalı daire — Nesimi ilçesi, Nizami Caddesi',
    titleEn: '3-room apartment — Nasimi district, Nizami Street',
    descAz: 'Nizami küçəsinin mərkəzində yerləşən, tam təmirli, mebelli 3 otaqlı mənzil. Binada lift, mühafizə və otopark mövcuddur. Metro stansiyasına piyada məsafədə.',
    descTr: 'Nizami Caddesi\'nin merkezinde yer alan, tam tadilatlı, mobilyalı 3 odalı daire. Binada asansör, güvenlik ve otopark mevcuttur. Metro istasyonuna yürüme mesafesinde.',
    descEn: 'Fully renovated 3-room apartment in the heart of Nizami Street. Building has elevator, security and parking. Walking distance to metro station.',
    category: 'SALE',
    propertyType: 'APARTMENT',
    price: 185000,
    currency: 'USD',
    area: 95,
    city: 'Bakı',
    district: 'Nəsimi',
    address: 'Nizami küçəsi 45, mənzil 12',
    rooms: 3,
    bathrooms: 1,
    floor: 7,
    totalFloors: 16,
    buildYear: 2018,
    hasParking: true,
    hasBalcony: true,
    hasElevator: true,
    hasFurniture: true,
    hasAC: true,
    hasInternet: true,
    hasSecurity: true,
    hasPool: false,
    hasGym: false,
    isFeatured: true,
    isNew: false,
    viewCount: 342,
    imagesJson: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80', alt: 'Salon', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80', alt: 'Yataq otağı' },
      { url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80', alt: 'Mətbəx' },
    ]),
  },
  {
    titleAz: 'Lüks villa — Badamdar qəsəbəsi',
    titleTr: 'Lüks villa — Badamdar köyü',
    titleEn: 'Luxury villa — Badamdar settlement',
    descAz: 'Badamdar qəsəbəsinin sakit küçəsində yerləşən 4 otaqlı lüks villa. Geniş həyət, hovuz, fitnes zalı və 2 qarajlı. Bakı şəhərinə gözəl mənzərə.',
    descTr: 'Badamdar köyünün sakin sokağında yer alan 4 odalı lüks villa. Geniş bahçe, yüzme havuzu, spor salonu ve 2 garaj. Bakü şehrine muhteşem manzara.',
    descEn: 'Luxurious 4-room villa on a quiet street in Badamdar. Spacious yard, swimming pool, gym and 2-car garage. Stunning views of Baku city.',
    category: 'SALE',
    propertyType: 'VILLA',
    price: 750000,
    currency: 'USD',
    area: 320,
    city: 'Bakı',
    district: 'Badamdar',
    address: 'Badamdar qəsəbəsi, Nar küçəsi 8',
    rooms: 4,
    bathrooms: 3,
    floor: null,
    totalFloors: 2,
    buildYear: 2021,
    hasParking: true,
    hasBalcony: true,
    hasElevator: false,
    hasFurniture: true,
    hasAC: true,
    hasInternet: true,
    hasSecurity: true,
    hasPool: true,
    hasGym: true,
    isFeatured: true,
    isNew: false,
    viewCount: 521,
    imagesJson: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80', alt: 'Villa', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80', alt: 'Hovuz' },
      { url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80', alt: 'Həyət' },
    ]),
  },
  {
    titleAz: '2 otaqlı mənzil icarəyə — Səbail rayonu',
    titleTr: '2 odalı daire kiralık — Sabail ilçesi',
    titleEn: '2-room apartment for rent — Sabail district',
    descAz: 'Dəniz görünüşlü, 2 otaqlı tam mebelli mənzil. İcarə qiyməti kommunal xərclər daxildir. Uzunmüddətli icarə üçün endirimlər var.',
    descTr: 'Deniz manzaralı, 2 odalı tam mobilyalı daire. Kira fiyatı faturalar dahildir. Uzun dönem kiralama için indirimler mevcuttur.',
    descEn: 'Sea-view 2-room fully furnished apartment. Rent price includes utilities. Discounts available for long-term lease.',
    category: 'RENT',
    propertyType: 'APARTMENT',
    price: 1200,
    currency: 'AZN',
    area: 68,
    city: 'Bakı',
    district: 'Səbail',
    address: 'İstiqlaliyyət küçəsi 23',
    rooms: 2,
    bathrooms: 1,
    floor: 5,
    totalFloors: 9,
    buildYear: 2015,
    hasParking: false,
    hasBalcony: true,
    hasElevator: true,
    hasFurniture: true,
    hasAC: true,
    hasInternet: true,
    hasSecurity: false,
    hasPool: false,
    hasGym: false,
    isFeatured: true,
    isNew: true,
    viewCount: 198,
    imagesJson: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80', alt: 'Salon', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?w=800&q=80', alt: 'Yataq otağı' },
    ]),
  },
  {
    titleAz: 'Ofis sahəsi icarəyə — Nərimanov rayonu',
    titleTr: 'Ofis alanı kiralık — Narimanov ilçesi',
    titleEn: 'Office space for rent — Narimanov district',
    descAz: 'Nərimanov rayonunun biznes mərkəzinde tam təchizatlı ofis sahəsi. Açıq plan, 2 kabinet, konfrans otağı. Özəl otopark daxildir.',
    descTr: 'Narimanov ilçesinin iş merkezinde tam donanımlı ofis alanı. Açık plan, 2 kabin, konferans odası. Özel otopark dahildir.',
    descEn: 'Fully equipped office space in Narimanov business center. Open plan, 2 cabinets, conference room. Private parking included.',
    category: 'RENT',
    propertyType: 'OFFICE',
    price: 3500,
    currency: 'AZN',
    area: 150,
    city: 'Bakı',
    district: 'Nərimanov',
    address: 'Həsən Əliyev küçəsi 78, Biznes Mərkəz',
    rooms: null,
    bathrooms: 2,
    floor: 3,
    totalFloors: 12,
    buildYear: 2019,
    hasParking: true,
    hasBalcony: false,
    hasElevator: true,
    hasFurniture: true,
    hasAC: true,
    hasInternet: true,
    hasSecurity: true,
    hasPool: false,
    hasGym: false,
    isFeatured: false,
    isNew: true,
    viewCount: 87,
    imagesJson: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80', alt: 'Ofis', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&q=80', alt: 'Konfrans otağı' },
    ]),
  },
  {
    titleAz: '1 otaqlı mənzil — Xətai rayonu',
    titleTr: '1 odalı daire — Hatai ilçesi',
    titleEn: '1-room apartment — Khatai district',
    descAz: 'Xətai rayonunda yeni tikili binada 1 otaqlı mənzil. Metrodan 5 dəqiqəlik məsafə. İlkin ödəniş şərtləri mövcuddur.',
    descTr: 'Hatai ilçesinde yeni bina 1 odalı daire. Metroya 5 dakika mesafe. Peşin ödeme koşulları mevcuttur.',
    descEn: '1-room apartment in new building in Khatai district. 5-minute walk to metro. Down payment options available.',
    category: 'SALE',
    propertyType: 'APARTMENT',
    price: 72000,
    currency: 'USD',
    area: 42,
    city: 'Bakı',
    district: 'Xətai',
    address: 'Koroğlu metrosunun yaxınlığı',
    rooms: 1,
    bathrooms: 1,
    floor: 4,
    totalFloors: 18,
    buildYear: 2023,
    hasParking: true,
    hasBalcony: true,
    hasElevator: true,
    hasFurniture: false,
    hasAC: false,
    hasInternet: false,
    hasSecurity: true,
    hasPool: false,
    hasGym: false,
    isFeatured: false,
    isNew: true,
    viewCount: 156,
    imagesJson: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80', alt: 'Mənzil', isPrimary: true },
    ]),
  },
  {
    titleAz: '4 otaqlı ev — Binəqədi rayonu',
    titleTr: '4 odalı ev — Binagadi ilçesi',
    titleEn: '4-room house — Binagadi district',
    descAz: 'Binəqədi rayonunda geniş həyəti olan 4 otaqlı ev. Qazı, suyu, elektriyi var. Sakit, yaşıllıqlı ərazidə.',
    descTr: 'Binagadi ilçesinde geniş bahçeli 4 odalı ev. Doğalgaz, su, elektrik mevcut. Sakin, yeşil bir alanda.',
    descEn: '4-room house with spacious yard in Binagadi district. Gas, water, electricity connected. Quiet, green area.',
    category: 'SALE',
    propertyType: 'HOUSE',
    price: 145000,
    currency: 'USD',
    area: 180,
    city: 'Bakı',
    district: 'Binəqədi',
    address: 'Binəqədi qəsəbəsi, Azadlıq küçəsi 12',
    rooms: 4,
    bathrooms: 2,
    floor: null,
    totalFloors: 2,
    buildYear: 2010,
    hasParking: true,
    hasBalcony: false,
    hasElevator: false,
    hasFurniture: false,
    hasAC: false,
    hasInternet: false,
    hasSecurity: false,
    hasPool: false,
    hasGym: false,
    isFeatured: false,
    isNew: false,
    viewCount: 93,
    imagesJson: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80', alt: 'Ev', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80', alt: 'Həyət' },
    ]),
  },
  {
    titleAz: 'Ticari əmlak — Nəsimi rayonu, Rəşid Behbudov',
    titleTr: 'Ticari mülk — Nesimi ilçesi, Reşit Behbudov',
    titleEn: 'Commercial property — Nasimi district, Rashid Behbudov',
    descAz: 'Rəşid Behbudov küçəsinin küncündə yerləşən, yüksək trafik sahəsində, 80 kv.m ticari sahə. Pərakəndə mağaza, restoran, kafe üçün idealdır.',
    descTr: 'Reşit Behbudov Caddesi\'nin köşesinde, yüksek trafikli alanda 80 m² ticari alan. Perakende mağaza, restoran, kafe için idealdir.',
    descEn: 'Commercial space on the corner of Rashid Behbudov Street in high-traffic area, 80 sqm. Ideal for retail store, restaurant, cafe.',
    category: 'RENT',
    propertyType: 'COMMERCIAL',
    price: 4500,
    currency: 'AZN',
    area: 80,
    city: 'Bakı',
    district: 'Nəsimi',
    address: 'Rəşid Behbudov küçəsi, 67',
    rooms: null,
    bathrooms: 1,
    floor: 1,
    totalFloors: 5,
    buildYear: 2005,
    hasParking: false,
    hasBalcony: false,
    hasElevator: false,
    hasFurniture: false,
    hasAC: true,
    hasInternet: true,
    hasSecurity: false,
    hasPool: false,
    hasGym: false,
    isFeatured: false,
    isNew: false,
    viewCount: 211,
    imagesJson: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80', alt: 'Mağaza', isPrimary: true },
    ]),
  },
  {
    titleAz: 'Torpaq sahəsi — Mərdəkan, Abşeron',
    titleTr: 'Arsa — Mardakan, Abşeron',
    titleEn: 'Land plot — Mardakan, Absheron',
    descAz: 'Mərdəkanda 6 sot torpaq sahəsi. Tikinti icazəsi var. Kommunikasiyalar — qaz, su, elektrik — yaxınlıqda mövcuddur. Dənizə 10 dəqiqəlik məsafə.',
    descTr: 'Mardakan\'da 6 dönüm arsa. Yapı izni mevcut. Altyapı — doğalgaz, su, elektrik — yakınlarda mevcut. Denize 10 dakika mesafe.',
    descEn: '6-acre land plot in Mardakan. Building permit available. Utilities — gas, water, electricity — nearby. 10 minutes to the sea.',
    category: 'SALE',
    propertyType: 'LAND',
    price: 55000,
    currency: 'USD',
    area: 600,
    city: 'Abşeron',
    district: 'Mərdəkan',
    address: 'Mərdəkan qəsəbəsi',
    rooms: null,
    bathrooms: null,
    floor: null,
    totalFloors: null,
    buildYear: null,
    hasParking: false,
    hasBalcony: false,
    hasElevator: false,
    hasFurniture: false,
    hasAC: false,
    hasInternet: false,
    hasSecurity: false,
    hasPool: false,
    hasGym: false,
    isFeatured: false,
    isNew: true,
    viewCount: 67,
    imagesJson: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80', alt: 'Torpaq', isPrimary: true },
    ]),
  },
  {
    titleAz: '3 otaqlı mənzil icarəyə — Yasamal rayonu',
    titleTr: '3 odalı daire kiralık — Yasamal ilçesi',
    titleEn: '3-room apartment for rent — Yasamal district',
    descAz: 'Yasamal rayonunun mərkəzində, tam mebelli, ideal vəziyyətdə 3 otaqlı mənzil. Ailə üçün uyğundur. İnfrastruktura yaxın.',
    descTr: 'Yasamal ilçesinin merkezinde, tam mobilyalı, mükemmel durumda 3 odalı daire. Aile için uygundur. Altyapıya yakın.',
    descEn: 'Fully furnished 3-room apartment in excellent condition in Yasamal center. Suitable for families. Close to infrastructure.',
    category: 'RENT',
    propertyType: 'APARTMENT',
    price: 900,
    currency: 'AZN',
    area: 85,
    city: 'Bakı',
    district: 'Yasamal',
    address: 'Cavid prospekti, 55',
    rooms: 3,
    bathrooms: 1,
    floor: 3,
    totalFloors: 9,
    buildYear: 2012,
    hasParking: false,
    hasBalcony: true,
    hasElevator: true,
    hasFurniture: true,
    hasAC: true,
    hasInternet: true,
    hasSecurity: false,
    hasPool: false,
    hasGym: false,
    isFeatured: true,
    isNew: false,
    viewCount: 278,
    imagesJson: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80', alt: 'Salon', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80', alt: 'Yataq otağı' },
    ]),
  },
  {
    titleAz: 'Penthouse — Şirvanşahlar prospekti, Səbail',
    titleTr: 'Penthouse — Şirvanşahlar Bulvarı, Sabail',
    titleEn: 'Penthouse — Shirvanshahlar Avenue, Sabail',
    descAz: '360 dərəcə panoramik mənzərəli lüks penthouse. 5 otaq, 3 vanna, 2 terras. Binada 24 saat mühafizə, konsyerj xidməti.',
    descTr: '360 derece panoramik manzaralı lüks penthouse. 5 oda, 3 banyo, 2 teras. Binada 24 saat güvenlik, konsiyerj hizmeti.',
    descEn: 'Luxury penthouse with 360-degree panoramic views. 5 rooms, 3 bathrooms, 2 terraces. 24-hour security and concierge service.',
    category: 'SALE',
    propertyType: 'APARTMENT',
    price: 1200000,
    currency: 'USD',
    area: 280,
    city: 'Bakı',
    district: 'Səbail',
    address: 'Şirvanşahlar prospekti, 1 Neftçilər Towers',
    rooms: 5,
    bathrooms: 3,
    floor: 28,
    totalFloors: 28,
    buildYear: 2022,
    hasParking: true,
    hasBalcony: true,
    hasElevator: true,
    hasFurniture: true,
    hasAC: true,
    hasInternet: true,
    hasSecurity: true,
    hasPool: true,
    hasGym: true,
    isFeatured: true,
    isNew: false,
    viewCount: 893,
    imagesJson: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80', alt: 'Salon', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800&q=80', alt: 'Terras' },
      { url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80', alt: 'Mənzərə' },
    ]),
  },
  {
    titleAz: '2 otaqlı mənzil — Suraxanı rayonu',
    titleTr: '2 odalı daire — Surakhani ilçesi',
    titleEn: '2-room apartment — Surakhani district',
    descAz: 'Suraxanı rayonunda əlverişli qiymətə 2 otaqlı mənzil. İpoteka ilə almaq mümkündür. Tikintisi yeni başa çatmış binadır.',
    descTr: 'Surakhani ilçesinde uygun fiyatlı 2 odalı daire. Mortgage ile satın alınabilir. Yeni bina.',
    descEn: 'Affordable 2-room apartment in Surakhani district. Mortgage available. Newly completed building.',
    category: 'SALE',
    propertyType: 'APARTMENT',
    price: 58000,
    currency: 'USD',
    area: 58,
    city: 'Bakı',
    district: 'Suraxanı',
    address: 'Suraxanı qəsəbəsi, Müstəqillik küçəsi',
    rooms: 2,
    bathrooms: 1,
    floor: 6,
    totalFloors: 14,
    buildYear: 2024,
    hasParking: true,
    hasBalcony: true,
    hasElevator: true,
    hasFurniture: false,
    hasAC: false,
    hasInternet: false,
    hasSecurity: true,
    hasPool: false,
    hasGym: false,
    isFeatured: false,
    isNew: true,
    viewCount: 134,
    imagesJson: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1591088398332-8a7791972843?w=800&q=80', alt: 'Mənzil', isPrimary: true },
    ]),
  },
  {
    titleAz: 'Həyət evi — Novxanı, Abşeron',
    titleTr: 'Müstakil ev — Novhani, Abşeron',
    titleEn: 'Detached house — Novkhani, Absheron',
    descAz: 'Novxanıda 10 sot ərazidə 5 otaqlı həyət evi. İki mərtəbə, qaraj, anbar. Şəhərə yaxın, rahat nəqliyyat.',
    descTr: 'Novhani\'de 10 dönüm arazide 5 odalı müstakil ev. İki kat, garaj, depo. Şehre yakın, rahat ulaşım.',
    descEn: '5-room detached house on 10-acre plot in Novkhani. Two floors, garage, storage room. Close to the city, convenient transport.',
    category: 'SALE',
    propertyType: 'HOUSE',
    price: 210000,
    currency: 'USD',
    area: 220,
    city: 'Abşeron',
    district: 'Novxanı',
    address: 'Novxanı qəsəbəsi, Şimal küçəsi 3',
    rooms: 5,
    bathrooms: 2,
    floor: null,
    totalFloors: 2,
    buildYear: 2017,
    hasParking: true,
    hasBalcony: true,
    hasElevator: false,
    hasFurniture: false,
    hasAC: false,
    hasInternet: true,
    hasSecurity: false,
    hasPool: false,
    hasGym: false,
    isFeatured: false,
    isNew: false,
    viewCount: 176,
    imagesJson: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80', alt: 'Ev', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1416331108676-a22ccb276e35?w=800&q=80', alt: 'Həyət' },
    ]),
  },
  {
    titleAz: 'Studio mənzil icarəyə — Nərimanov, yeni tikili',
    titleTr: 'Stüdyo daire kiralık — Narimanov, yeni bina',
    titleEn: 'Studio apartment for rent — Narimanov, new building',
    descAz: 'Nərimanov rayonunda yeni tikili binada müasir dizaynlı studio mənzil. Tələbə və gənc mütəxəssislər üçün əla seçim.',
    descTr: 'Narimanov ilçesinde yeni binada modern tasarımlı stüdyo daire. Öğrenci ve genç profesyoneller için mükemmel seçim.',
    descEn: 'Modern studio apartment in new building in Narimanov. Great choice for students and young professionals.',
    category: 'RENT',
    propertyType: 'APARTMENT',
    price: 500,
    currency: 'AZN',
    area: 35,
    city: 'Bakı',
    district: 'Nərimanov',
    address: 'Atatürk prospekti, 102',
    rooms: 1,
    bathrooms: 1,
    floor: 9,
    totalFloors: 20,
    buildYear: 2023,
    hasParking: false,
    hasBalcony: false,
    hasElevator: true,
    hasFurniture: true,
    hasAC: true,
    hasInternet: true,
    hasSecurity: true,
    hasPool: false,
    hasGym: true,
    isFeatured: false,
    isNew: true,
    viewCount: 245,
    imagesJson: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&q=80', alt: 'Studio', isPrimary: true },
    ]),
  },
  {
    titleAz: '5 otaqlı mənzil — Xəzər rayonu, Buzovna',
    titleTr: '5 odalı daire — Hazar ilçesi, Buzovna',
    titleEn: '5-room apartment — Khazar district, Buzovna',
    descAz: 'Buzovnada dəniz görünüşlü, geniş 5 otaqlı mənzil. Böyük terras, 2 qaraj, qapalı hovuz. İl boyu yaşamaq üçün idealdır.',
    descTr: 'Buzovna\'da deniz manzaralı, geniş 5 odalı daire. Büyük teras, 2 garaj, kapalı yüzme havuzu. Yıl boyunca yaşamak için idealdir.',
    descEn: 'Spacious sea-view 5-room apartment in Buzovna. Large terrace, 2 garages, indoor pool. Ideal for year-round living.',
    category: 'SALE',
    propertyType: 'APARTMENT',
    price: 420000,
    currency: 'USD',
    area: 230,
    city: 'Bakı',
    district: 'Buzovna',
    address: 'Buzovna qəsəbəsi, Dəniz küçəsi 15',
    rooms: 5,
    bathrooms: 2,
    floor: 4,
    totalFloors: 6,
    buildYear: 2020,
    hasParking: true,
    hasBalcony: true,
    hasElevator: true,
    hasFurniture: true,
    hasAC: true,
    hasInternet: true,
    hasSecurity: true,
    hasPool: true,
    hasGym: false,
    isFeatured: true,
    isNew: false,
    viewCount: 412,
    imagesJson: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80', alt: 'Salon', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80', alt: 'Terras' },
      { url: 'https://images.unsplash.com/photo-1599619351208-3e6c839d6828?w=800&q=80', alt: 'Hovuz' },
    ]),
  },
  {
    titleAz: 'Anbar sahəsi icarəyə — Abşeron şossesi',
    titleTr: 'Depo alanı kiralık — Abşeron Şosesi',
    titleEn: 'Warehouse for rent — Absheron Highway',
    descAz: 'Abşeron şossesinin yaxınlığında 500 kv.m sənaye anbarı. Yüksük tavan, böyük qapı, daxili yola çıxışı var. Logistika üçün əla.',
    descTr: 'Abşeron Şosesi yakınında 500 m² endüstriyel depo. Yüksek tavan, büyük kapı, iç yola erişim. Lojistik için mükemmel.',
    descEn: '500 sqm industrial warehouse near Absheron Highway. High ceilings, large door, internal road access. Excellent for logistics.',
    category: 'RENT',
    propertyType: 'COMMERCIAL',
    price: 2800,
    currency: 'AZN',
    area: 500,
    city: 'Bakı',
    district: 'Abşeron şossesi',
    address: 'Abşeron şossesi, km 12',
    rooms: null,
    bathrooms: 1,
    floor: 1,
    totalFloors: 1,
    buildYear: 2008,
    hasParking: true,
    hasBalcony: false,
    hasElevator: false,
    hasFurniture: false,
    hasAC: false,
    hasInternet: false,
    hasSecurity: true,
    hasPool: false,
    hasGym: false,
    isFeatured: false,
    isNew: false,
    viewCount: 58,
    imagesJson: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80', alt: 'Anbar', isPrimary: true },
    ]),
  },
];

async function main() {
  console.log('Seeding database...');
  await prisma.listing.deleteMany();
  await prisma.contactMessage.deleteMany();

  for (const listing of listings) {
    await prisma.listing.create({ data: listing });
  }

  console.log(`Created ${listings.length} listings.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
